# Netlify Configuration for Vakıf Dashboard
# Next.js App Router Deployment

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

# Supabase environment variables
# Netlify Dashboard > Site settings > Environment variables'da ayarlayın:
# NEXT_PUBLIC_SUPABASE_URL = https://your-project.supabase.co
# NEXT_PUBLIC_SUPABASE_ANON_KEY = your-anon-key-here

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["lib/**", "public/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# PDF upload size limit
[[headers]]
  for = "/api/upload-pdf"
  [headers.values]
    Content-Length = "10485760"  # 10MB 